version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prueba-kuantaz-app
    container_name: prueba-kuantaz-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: prueba-kuantaz-app
      SERVICE_TAGS: dev
      APP_NAME: prueba-kuantaz
      APP_ENV: local
      APP_KEY: base64:KZl4gGNw0+LpJiuCF2zcdjMtPVfsUylUKw7iaRKUUYE=
      APP_DEBUG: "true"
      APP_URL: http://localhost
    working_dir: /var/www/html
    volumes:
      - C:\prueba-kuantaz:/var/www/html
    networks:
      - app-network

  web:
    image: 'nginx:alpine'
    ports:
      - "8000:80"
    volumes:
      - C:\prueba-kuantaz:/var/www/html  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge